### ISSUE TITLE
Incorrect epistasis layer for W-model problem.

### ISSUE THREAD

**Issue by 18756** [IOHprofiler/IOHexperimenter#119]
https://github.com/IOHprofiler/IOHexperimenter/blob/master/include/ioh/problem/wmodel/wmodel_problem.hpp#L86
the input and result binary vectors are the same, so during the epistasis evaulation, the intermediate results affect the final result.
Due to this, the target bit string and fitness values of the W-model problem with epistasis values higher than 2 are incorrect.

Simple Example (see Fig.2 in Weise and Wu, 2018): 
epi = 4
in = [1, 0, 0, 0]
current implementation works as follows:
1) in = 1000, set 1 to 4th bit (1 xor 0 xor 0 xor 0 = 1)
2) in = 1001, set 1 to 3th bit (1 xor 0 xor 0 = 1) 
3) in = 1011, set 0 to 2nd bit (1 xor 1 xor 0 = 0)
4) in = 1011, set 1 to 1st bit (1 xor 1 xor 1 = 1)

actual result = [1, 0, 1, 1] with fitness value of 3.

expected implementation should have input and result vectors different:
in = [1, 0, 0, 0]
res = [0, 0, 0, 0]

1) res = 0000, set 1 to 4th bit (1 xor 0 xor 0 xor 0 = 1)
2) res = 0001, set 1 to 3th bit (1 xor 0 xor 0 = 1) 
3) res = 0011, set 1 to 2nd bit (1 xor 0 xor 0 = 1)
4) res = 0111, set 1 to 1st bit (1 xor 0 xor 0 = 1)

expected res = [1, 1, 1, 1]

**Comment by vmironovich** [comment]
Notably, this is not an issue with neutrality layer, as input vector is copied there. https://github.com/IOHprofiler/IOHexperimenter/blob/8a49d76d591c52b4ae8ed0991d4b6ea8d5c3adaa/include/ioh/problem/utils.hpp#L183

So, the fix for the epistasis probably can be as simple as making the first argument of the layer_epistasis_compute a copy too. https://github.com/IOHprofiler/IOHexperimenter/blob/8a49d76d591c52b4ae8ed0991d4b6ea8d5c3adaa/include/ioh/problem/utils.hpp#L261

**Comment by FurongYe** [comment]
My apologies for replying this late. I somehow overlooked this message.

Sorry that I did not get the later part of the issue. What are the input and the expected output? 
The proposed issue is caused by the way of counting the index. The direction counting index (from left to right) in the implementation is different from the way in the literature (from right to left). A cheating table of the transformation results can also be found in https://doi.org/10.1016/j.asoc.2019.106027 .

**Comment by 18756** [comment]
expected: e4(1000) = 1111 (from BOX I https://doi.org/10.1016/j.asoc.2019.106027)
actual: e4(1000) = 1011

**Comment by FurongYe** [comment]
> expected: e4(1000) = 1111 (from BOX I https://doi.org/10.1016/j.asoc.2019.106027)
> actual: e4(1000) = 1011

The '1000' in the program is '0001' in the literature counting from the right, so e4(0001) = 1101 ('1011' in the programe). Sorry for the confusion here.
