### ISSUE TITLE
Star Discrepancy optimum value

### ISSUE THREAD

**Issue by dani2221** [IOHprofiler/IOHexperimenter#168]
when calling problem.optimum on any star discrepancy the output looks like this:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/55097438/235220387-46000e76-69d0-4187-829e-478cc5152dbd.png">
Which is obviously not the right answer. Tested on Star Discrepancy Integer and Star Discrepancy Real and encountered the problem on both.

**Comment by borisalmonacid** [comment]
`y` is the fitness value???

**Comment by jacobdenobel** [comment]
Hi,
For star discrepancy problems the optimum is unknown. While we should be able to compute this for simpler problems in lower dimensions, this becomes infeasible for problems of higher dimensionality/number of points. Therefore, we decided not to provide any information on the optimum for any star discrepancy problems, which is why we only return the value (0, 0), inf for the location of the optimum, which basically means the optimum is unknown.

**Comment by jacobdenobel** [comment]
> 

Yes
